SELECT * FROM student

SELECT * FROM  student WHERE AGE BETWEEN 10 AND 20;
SELECT NAME FROM student;
SELECT * FROM student WHERE  NAME  LIKE '%o%' OR NAME  LIKE '%O%'
SELECT * FROM student WHERE AGE < id;
SELECT * FROM student ORDER BY AGE;